### ISSUE TITLE
CY1 Turma #1405

### ISSUE THREAD

**Issue by f203606** [f203606/CY1#1]
Olá, ,pessoal. Vocês tem algo a dizer?

**Comment by AaronSouza-Ctrl** [comment]
jhguyuihjygbvytdfvgbfklnghjjklkpjohiuy8ijuhgvcfdxrtfyuioopipijgbvyrtf54etyhujkl,pkoj9p98ihydfxsrzawsedfhgbvcgfhvgjnbuf gvkjcgfbvdyrgbfdhgfdrvrjrtfxytvrcexwza64tbjkhgfdrtyui98uy7cfdr4y5hjbgvfcddefkmliun8y76g5regfhgjdrvtcqaascdvblkmojiuy67tgfcfjvghngcdtr554rtgnnbjhgyvfrruijohgfvcdrfgthjmhngbfdretyyfhnyryetfgdtryuhjugfdr567uyinhvgfcdejiu7ybgjnhgkfvhctdefghjknhgvfcdxseza

**Comment by f203606** [comment]
`print("Hello, World!)`

**Comment by ronaldo1223** [comment]
olá,seja bem vindo ao cna fisk,aqui você aprende inglês,espanhol,português,informática e muito mais.

**Comment by AaronSouza-Ctrl** [comment]
`arquivo = open('ponto_float.txt')
ponto=int(arquivo.read())
if 0 <= ponto <= 25:
    print('intervalo [0,25]')
elif 25 < ponto <= 50:
    print('intervalo [25, 50]')
elif 50 < ponto <= 75:
    print('intervalo [50, 75]')
elif 75 < ponto <= 100:
    print('intervalo [75, 100]')
else:
    print('fora de intervalo')`

**Comment by Gabriel88844** [comment]
`print('SANTA CRUZ é melhor que o São Paulo') `

**Comment by f203606** [comment]
### Aqui tem um título.

**Comment by f203606** [comment]
#####Aqui tem outro título.

**Comment by Gabriel88844** [comment]
### CAÇA RATOOOOOO!!!!!!

**Comment by AaronSouza-Ctrl** [comment]
### Título titulado

**Comment by Gabriel88844** [comment]
1. acordei
2. foi pra escola
3. voltei pra casa
4. vim pro curso

**Comment by f203606** [comment]
1. Acordei
2. Tomei café
3. Fui trabalhar na Ctrl+Play
4. Busquei minhas filhas na escola
5. Voltei pra Ctrl+Play

**Comment by digo2005** [comment]
1 acordei
2 tomei cafe
3 fui na hidro seja israel ou seja webber
4 fui almoçar
5 fui ao ingles seja cna ou seja fisk 
6 descansei
7 fui na robótica

**Comment by f203606** [comment]
- [ ] Tarefa da escola
- [ ] Tarefa de casa
- [ ] Varrer casa
- [ ] Tirar lixo

**Comment by Gabriel88844** [comment]
- [ ]lavar a louça
- [ ]trabalho da escola

**Comment by digo2005** [comment]
varrer a casa limpar os pratos lavar a louça

**Comment by Gabriel88844** [comment]
- [ ] lavar a louça
- [ ] trabalho da escola

**Comment by AaronSouza-Ctrl** [comment]
1. acordei
2. me arrumei para ir ao colégio
3. tomei o café da manhã
4. fui ao colégio
5. almocei
6. estudei para a prova de amanhã
7. tomei banho
8. me arrumei pra aula Ctrl Play
9. tomei o café da tarde
10. fui ao Ctrl Play Capão Raso
11. afundei o teclado na aula

**Comment by digo2005** [comment]
varrer a casa
limpar os pratos
lavar a louça

**Comment by f203606** [comment]
[https://www.linkedin.com/in/andr%C3%A9-souza-47937b15/](url)

**Comment by AaronSouza-Ctrl** [comment]
https://openai.com/chatgpt/

**Comment by Gabriel88844** [comment]
[https://www.youtube.com/watch?v=t7Ksals5HM0](url)

**Comment by Gabriel88844** [comment]
[https://www.youtube.com/watch?v=t7Ksals5HM0]

**Comment by Gabriel88844** [comment]
[www.youtube.com/watch?v=t7Ksals5HM0](url)

**Comment by Gabriel88844** [comment]
![d5fd5ac55a585e522947a2146a0e63fa](https://github.com/user-attachments/assets/d38a24d8-a91b-4459-b9cf-8fa53f27d61c)

**Comment by f203606** [comment]
Pessoal. Aqui está minha assinatura.

![Assinatura GitHub](https://github.com/user-attachments/assets/13efa547-c1d9-4ead-961c-dab33bd12f93)

**Comment by Gabriel88844** [comment]
essa é minha assinatura

![d5fd5ac55a585e522947a2146a0e63fa](https://github.com/user-attachments/assets/e55c4b95-dc2a-4584-b5db-bd6c6856b69a)

**Comment by f203606** [comment]
![Foto de perfil - GitHub](https://github.com/user-attachments/assets/1bbde12a-0f7c-488a-8c1f-7a7cad3dbc1a)

**Comment by AaronSouza-Ctrl** [comment]
![Sunglasses Emoji](https://github.com/user-attachments/assets/e6e56f01-1b67-400f-9d29-a96e4ea5bb6d)

**Comment by AaronSouza-Ctrl** [comment]
@f203606

**Comment by f203606** [comment]
- [ ] @AaronSouza-Ctrl 
- [ ] @digo2005 @
- [ ] @Gabriel88844

**Comment by f203606** [comment]
Onde está o erro:

`for cont in range (0, 10)`
`        print(cont)`

**Comment by Gabriel88844** [comment]
falta os dois pontos no final da primeira linha

**Comment by AaronSouza-Ctrl** [comment]
está faltando os dois pontos no final do código da primeira linha

**Comment by digo2005** [comment]
for cont in range (0, 10):print(cont)

Em qui., 3 de out. de 2024 às 20:18, AaronSouza-Ctrl <
***@***.***> escreveu:
